// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dffhmzdqdmesoigksudw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmZmhtemRxZG1lc29pZ2tzdWR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjcwMzksImV4cCI6MjA3NDQwMzAzOX0.6IL7tzGQ9yzdu-QzjM4jVPOUYF5f5ozczGLDvKR9GTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);